#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import re
import sys

from igpay import igpay

def igpay_enhance(string):
    """
    if string.endswith(('.', ',', '?', ':', '\t')):
        suffix, string = string[-1], string[:-1]
    else:
        suffix = ''
    """
    if string.islower():
        return igpay(string)# + suffix

    if string.isupper():
        return igpay(string.lower()).upper()# + suffix

    if string.istitle():
        return igpay(string.lower()).title()# + suffix

    return string

def main():
    if len(sys.argv) < 2:
        print("Usage: ./atinly <filename>")
        return
    filepath = sys.argv[1]
    with open(filepath, 'r') as f:
        for lines in f:
            strings = [igpay_enhance(string) for string in re.split('(\W)', lines) if string]
            #print(strings)
            print(''.join(strings), end='')



if __name__ == "__main__":
    # chmod +x ./atinly
    # ./atinly
    main()
